Final project - Back end
sheylaPozo/backend-finalcapstone pull request #4
Opened 2022-01-21 08:35 UTC by sheylaPozo

##### Front end PR
----
## Final project - Back end
**Database:**

- Usage: PostgreSql.
- Created tables: user, flats, reservations, cities.

_Models:_

- All associations are added to the models, so the relations made into the database between the tables, can be used in rails as well.
- All validations are added to the models, in order to avoid incorrect "inputs values" from a user into the database.

_Controllers:_
**Users:**

-:create is used to add a new object of user to the database.
- :destroy is used to delete a user from the database.
- private method that ensures that a specific parameter is present and avoid penetration into the project. As someone from outside to get an id of user and get personal information.

**Flats:**

:index is used to list all the flats from the database.
:create is used to add a new object of flat to the database.
:destroy is used to delete a flat from the database.
private method that ensures that a specific parameter is present and avoid penetration into the project. As someone from outside to get an id of user and get personal information.

**Reservations:**

:index is used to list all the reservations that a current User has.
:create is used to add a new object of reservation to the database.
:destroy is used to delete a reservation from the database.
private method that ensures that a specific parameter is present and avoid penetration into the project. As someone from outside to get an id of user and get personal information.

**Routes:**

The routes are created for each method in the controllers, in order the to create endpoints of the Api.

**API Documentation:**

API Documentation is created, so the Api can be easily used by users.

**_Contributors:_**
@2bleO

Thank you for taking the time to review our PR! 😃😁📌

2022-01-21 12:36 UTC, MuriloRoque requested changes
Hi @sheylaPozo, @2bleO, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:

- [ ] Adding some tests would be great.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-01-21 12:36 UTC, MuriloRoque commented on app/controllers/api/v1/cities_controller.rb
> +          city.reservations&.delete_all
- [ ] Take a look [here](https://guides.rubyonrails.org/association_basics.html#options-for-belongs-to-dependent), you can use `dependent` in `has_many` to automatically destroy all reservations, wouldn't that be better?

2022-01-21 12:36 UTC, MuriloRoque commented on config/routes.rb
> +      resources :flats
- [ ] This creates all routes, including unused ones, I would select only the ones I'm using.

2022-01-21 12:36 UTC, MuriloRoque commented on config/routes.rb
> +      resources :cities
- [ ] This creates all routes, including unused ones, I would select only the ones I'm using.

2022-01-21 12:36 UTC, MuriloRoque commented on app/controllers/pages_controller.rb
> +end
- [ ] Are you using this controller? If not, it's better to delete it.

2022-01-22 00:44 UTC, merged

2022-01-22 00:44 UTC, sheylaPozo commented
thank youu !!